### 矩阵分析作业1

In [2]:
import numpy as np

mat_a = np.array([[1, 2, 1],
                  [0, 1, 1],
                  [-1, 1, 1]])
mat_b = np.array([[0, -1, 1],
                  [1, 1, 2],
                  [1, 0, 1]])
B = np.linalg.inv(mat_a) @ mat_b
print(B)

[[-2.22044605e-16  1.00000000e+00  1.00000000e+00]
 [-1.00000000e+00 -3.00000000e+00 -2.00000000e+00]
 [ 2.00000000e+00  4.00000000e+00  4.00000000e+00]]


In [1]:
import numpy as np
mat_a = np.array([[23,3],
                  [3,15]])
mat_b = np.array([-12,36])
ans = mat_a@mat_b.T/14/7
print(ans)

[-1.71428571  5.14285714]


In [5]:
import numpy as np
def solve_E(x,a,g):
    return x.T@x/(g@(x.T))-a@(g.T)@g@a/(g@a@(g.T))
x = np.array([[45/7,15/7]])
a = np.eye(2)
g = np.array([[75/7,-15/7]])
ans = solve_E(x,a,g)
# print(ans)