### 矩阵分析作业1

In [2]:
import numpy as np

mat_a = np.array([[1, 2, 1],
                  [0, 1, 1],
                  [-1, 1, 1]])
mat_b = np.array([[0, -1, 1],
                  [1, 1, 2],
                  [1, 0, 1]])
B = np.linalg.inv(mat_a) @ mat_b
print(B)

[[-2.22044605e-16  1.00000000e+00  1.00000000e+00]
 [-1.00000000e+00 -3.00000000e+00 -2.00000000e+00]
 [ 2.00000000e+00  4.00000000e+00  4.00000000e+00]]
